version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "*"
    update-types: ["version-update:semver-patch"]
  - dependency-name: webpack
    versions:
    - 5.20.1
    - 5.26.3
    - 5.28.0
    - 5.33.2
    - 5.34.0
  - dependency-name: css-loader
    versions:
    - 5.1.0
    - 5.2.3
  - dependency-name: underscore
    versions:
    - 1.13.0
  - dependency-name: chai
    versions:
    - 4.3.2
