language: node_js
node_js:
- stable
addons:
  chrome: stable
before_install:
- npm install -g npm
install: npm install
script:
  - make
env:
  global:
    secure: MjADfurIdOxiILcoEg6DgYwotk01IC/hQOh8GD1BJewEgmDRBGwUwei37rhJRLDDjv+ciwLWfKdVAXbQzDPszFeux9dvzRoaVqkJ9wg3JajwAhOLwJZnoqBIbFRsM6HMj4m/zsk71EO9K4LiHAQojE19wgBB5/9FeNIf+TGHz9shpf5NwfMBSECZEOxr4mLU34GpaYIXAhBAsbFZeeJXaYVyYGzBpJzGm2qyH/EEFyjdsP+J7eJc/mKOBOxDErE7ZoJIzGdQEDol/fE3lKUNuLvcgU3/AGmGtimrj7JQL0wt5eCDJCwBRNh7CPlEiXgqM3Mw3f99eYLRxaX4QRwoB7HJ49H0+bdSr0l/vjPgqQuTQn8J8S/aY5FLHHoobTwsleQvDEFPc/PZRM3ZVFGRqH4aQazoaDtFTrFWAx2b1JsvnppOYmZzk3/Yf2JYVUqgsR6xhITuQ/4duirevTovCAdhHnP9K5SdXxTE4Rt50FDB2zDpo2ewBXpVTfJPpZhH+Gsmi+DWjplYRRzCLJWXQ7l+cNXtaORHahXo+SKIcC9DxhbqJuhOel6QEL+/eWc+fBGCsjCED9kIqqLc7JonEyR5QH9jYyg01RHB6BL/DIrChmedoamPaAeGWXvDc1AvvA06J5Ag9ZpTC9sfj9iPFtHlnuBEErb70fMQ39a6SUQ=
